# Type of NLP technique

POS part of speech -> analyse grammatical structure of sentences 



In [8]:


import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

%matplotlib inline
sns.set_style("whitegrid")
plt.style.use("fivethirtyeight")



Converting text into a matrx of token counts

In [13]:
# Example text for model training (SMS messages)
simple_train = ['call you tonight', 'Call me a cab', 'Please call me... PLEASE!']

# Import CountVectorizer from scikit-learn
from sklearn.feature_extraction.text import CountVectorizer

# Instantiate CountVectorizer (with the default parameters)
vect = CountVectorizer()

# Learn the 'vocabulary' of the training data (occurs in-place)
vect.fit(simple_train)

# Examine the fitted vocabulary
vocabulary = vect.get_feature_names_out()
print("Vocabulary :",vocabulary)

# Optionally, you can transform the training data to a document-term matrix
X_train = vect.transform(simple_train)
print("\nDocument-term matrix:\n", X_train.toarray())

pd.DataFrame(X_train.toarray(), columns=vect.get_feature_names_out())


Vocabulary : ['cab' 'call' 'me' 'please' 'tonight' 'you']

Document-term matrix:
 [[0 1 0 0 1 1]
 [1 1 1 0 0 0]
 [0 1 1 2 0 0]]


cab  call  me  please  tonight  you
0    0     1   0       0        1    1
1    1     1   1       0        0    0
2    0     1   1       2        0    0

In [14]:


# example text for model testing
simple_test = ["please don't call me"]
# transform testing data into a document-term matrix (using existing vocabulary)
simple_test_dtm = vect.transform(simple_test)
simple_test_dtm.toarray()
# examine the vocabulary and document-term matrix together
pd.DataFrame(simple_test_dtm.toarray(), columns=vect.get_feature_names_out())

cab  call  me  please  tonight  you
0    0     1   1       1        0    0